version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./:/config/:rw
    network_mode: host